### ISSUE TITLE
is there a proper tutorial or method 

### ISSUE THREAD

**Issue by zenji-png** [whowechina/chu_pico#1]
just the title

**Comment by zenji-png** [comment]
also how does it register input? there is no touch sensor?

**Comment by whowechina** [comment]
Of course there's touch sensor: capactive sense.
The readme in both EN and CN is the guide telling you how to build one.
But there won't be anything related to game data.

**Comment by zenji-png** [comment]
oh wait i think my question was wrong what i meant to say is something more like, the touch sensors aren't under the keys so how does it register?

**Comment by whowechina** [comment]
I see. So it's about "how the touch sensors work". The touch sensors (electrodes) are actually under the slider panel, built-in with the PCB. Search for MPR121 datasheet, or search "capsense", you'll understand.

**Comment by zenji-png** [comment]
thanks for the response i was thinking if it was something like that
