### ISSUE TITLE
LED problem

### ISSUE THREAD

**Issue by sksjndn3** [whowechina/chu_pico#4]
Chinese plz。
刷了led测试程序，在d13就不亮了，万用表测了下正常导通，灯也换了好几个，就是d13往后都不亮，是不是程序有问题
![1721718887796](https://github.com/user-attachments/assets/e2a741e9-a22c-4bfd-9d09-a913b25da103)
![qq_pic_merged_1721718923068](https://github.com/user-attachments/assets/d418bc0d-8a35-464d-aec5-1b60a25542cd)

**Comment by whowechina** [comment]
信号是串联传递的，一般 D13 故障，就要同时看 D12/D13 的焊接。

**Comment by sksjndn3** [comment]
我用万用表打了导通挡，全引脚都是正常导通的，还是不亮

**Comment by sksjndn3** [comment]
我再排除一下吧，谢谢大佬回复

**Comment by whowechina** [comment]
> 我再排除一下吧，谢谢大佬回复

除了“通”，要关注不应该通的，比如 D12 通往 D13 的数据线，不应该碰上 G 或者 V。
