### ISSUE TITLE
i2c/touch problem

### ISSUE THREAD

**Issue by sksjndn3** [whowechina/chu_pico#5]
我在焊接完毕后，烧录chupico固件后注意到灯乱闪，然后拆焊下来，在chuntest测试程序里发现一直在凭空触发所有区块，随后我又拿了一片完全全新的树莓派pico烧录chupico固件，也是这样乱跳，我找不到解决方案，多次重刷固件也无果
![Screenshot_2024-07-28-22-56-18-00_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/user-attachments/assets/e9880f09-833b-4ba8-9c0c-9aa30e0e5995)

**Comment by whowechina** [comment]
Touch 传感由 MPR121 模块完成，这个模块未连接或者连接故障就会导致错误的触摸检测。
使用命令行里面的多个命令，尤其是“raw”来进行调试，正常情况下，各个电极感应数据都在 850-900 附近。
因为这个不是 Chu Pico 本身的问题，我就关闭这个 Issue 了。

**Comment by sksjndn3** [comment]
好的吧，那我再排查一下3个mpr模块的问题，不过之前焊的两片板子都是通电正常亮灯来着

**Comment by sksjndn3** [comment]
也不对吧，我先前焊的四片pcb都是先测灯光完好性再焊触摸模块的，也没这样抽风闪灯😢

**Comment by whowechina** [comment]
灯光测试有一个专门的 UF2 文件，它不读触摸，仅仅点灯。
触摸模块或者 I2C 故障的时候，现象是随缘的。

**Comment by sksjndn3** [comment]
这问题很玄乎啊，3片mpr都是没有故障的之前焊的板子都是先测灯再上触摸，也没见这种抽搐，上了完好触摸也无济于事，raw读数照样抽风，进test也乱闪
![17224245774084844575459222361528](https://github.com/user-attachments/assets/fb45afb0-0bfa-4550-8da8-c548a0c34d7a)

这是另一片没焊触摸，触摸灯光和raw读数完全正常
![17224246371141034371022285045713](https://github.com/user-attachments/assets/b145361f-3817-49ef-b1d8-b034151922b6)

**Comment by whowechina** [comment]
使用chu_pico_led_test.uf2进行led测试，这个固件也只能测试led。

触摸故障的话，记得mpr121模块本身坏的概率极其低，更多是焊接，割addr线等事情。电子制作嘛，啥失误都可能。

**Comment by sksjndn3** [comment]
不对不对，我是说触摸数据在没有焊触摸模块的时候乱跳，这就说明锅甩不到mpr头上，何况焊了和没焊的乱跳表现都是一样的😞

**Comment by whowechina** [comment]
没焊好，或者没挂模块，都是一回事，都是触摸故障。 具体现象根据i2c俩引脚环境随缘了。在 2024年7月31日，22:48，sksjndn3 ***@***.***> 写道：﻿
不对不对，我是说触摸数据在没有焊触摸模块的时候乱跳，这就说明锅甩不到mpr头上，何况焊了和没焊的乱跳表现都是一样的😞
