### ISSUE TITLE
There's just two problem.

### ISSUE THREAD

**Issue by crazyforsf** [whowechina/chu_pico#6]
Using a translator. I'm Korean.

=================================================================

I think using a ToF sensor is a pretty good idea, but there are two problems with this form.

-
First, if the air sensor is being recognized in the 'center' and the touch has to be crossed with the other hand, the air sensor recognition is blocked by the other arm.
(ex : gengaozo expert, screenshot from Youtube)
![genga](https://github.com/user-attachments/assets/7bb3a01b-db33-4849-a0df-d3d16a8a5841)

Of course, being aware of that part, I can move my hand to the air sensor, but it is quite difficult to do so during complex processing of high difficulty level - master level 13+ or higher.

Therefore, it is good to use a ToF sensor, but I think it would be a better choice to have separate key assignment options or builds for each sensor, rather than depending on the 'height' of the ToF sensor.
(By placing the ToF sensor sideways like a conventional IR sensor)

-
Secondly, this is not a problem for this small controller, but if you make a full size controller the number of tof sensors is not enough.

There are some empty spaces in between.

Therefore, it is judged to be a good idea to allocate the maximum connection value of the TCA9548APWR chip to the ToF sensor. From the current 5 to the maximum of 8.

![openithm+chupico](https://github.com/user-attachments/assets/18de2a1a-7a7f-44f2-9bb8-5cde0c240713)

This is Openithm+chupico, which I created by modifying various things myself. It's a little unfinished.
(Never mind about having more sensors. It's not working right now so I've reduced it back to 5.)

It's arcade full size, and I think it works pretty well.

===================================================================

This is just a suggestion, and there is no pressure to ask why not make the offer.
I just think it would be better if these areas were improved.

**Comment by whowechina** [comment]
Hey, thanks for the feedback.
For the first problem, I can't do anything so far. Honestly I don't see a solution there for such a small con.
For the second problem, you can check my chu_arcade repo. I used 10+ ToF sensors for my arcade size con. 

https://github.com/user-attachments/assets/cb141b87-1fb6-4556-abc9-fbacf5f58e4d
