### ISSUE TITLE
air乱序

### ISSUE THREAD

**Issue by ifaming** [whowechina/chu_pico#8]
你好，我发现使用tof模式下的air从下往上触发顺序是2 3 4 1 5 6，而不是1 2 3 4 5 6，这是故意这样设计的还是说这是一个bug？

**Comment by whowechina** [comment]
按照 redboard chunio 来的。

**Comment by whowechina** [comment]
我确认后会修改。

**Comment by whowechina** [comment]
感谢，确实有问题，我已经修复。

Thank you. I've fixed it in latest commit.
